course_info_csv = """Course name,credit,semester,Lecturer,Lecture,ws
Numerical Linear Algebra,10,1,Dr Jacques Vanneste,2*1,1*1
Python Programming,10,1,Dr Charlotte Desvages,1*1,2*2
Research Skills for Computational Applied Mathematics,20,1,Prof Benedict Leimkuhler,1*1,1*1单
Applied Stochastic Differential Equations,10,1,Dr Kostas Zygalakis,2*1,2*1单
Statistical Methodology,10,1,Dr Victor Elvira Arregui,2*1,1*1双
Stochastic Modelling,10,1,Dr Theo Assiotis,2*1,1*2单
Fundamentals of Optimization,10,1,Prof Alper Yildirim,1*2,1*2单
Statistical Programming,10,1,Prof Simon Wood,2*1,1*1
Bayesian Theory,10,1,Prof Finn Lindgren,1*2,1*1单
Introductory Probability and Statistics,10,1,Dr Skarleth Carrales Escobedo,2*1,1*1
Industrial Mathematics,10,1,Dr Benjamin Goddard,1*1,2*1
Stochastic Analysis in Finance,20,1,Prof Istvan Gyongy,2*2,1*1
Discrete-Time Finance,10,1,Dr Tibor Antal,1*1,1*1双
"Finance, Risk and Uncertainty",10,1,Dr Jiawei Li,2*1,1*1
Fundamentals of Operational Research,10,1,Dr Sergio Garcia Quiles,2*1,1*1双
"Methodology, Modelling and Consulting Skills",10,1,Dr Kit Searle,2*1,1*1
Generalised Regression Models,10,1,Prof Patrick Rubin-Delanchy,1*2,1*1单
Extended Statistical Programming,20,1,Prof Simon Wood,2*1,1*1
"""

student_courses_csv = """Student ID,Semester 1 Courses
Student 1,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Topics in Applied Operational Research', 'Machine Learning in Python', 'Biostatistics']"
Student 2,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Machine Learning in Python', 'Optimization Methods in Finance', 'Generalised Regression Models']"
Student 3,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Machine Learning in Python', 'Biostatistics', 'Stochastic Modelling']"
Student 4,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Credit Scoring', 'Simulation', 'Time Series']"
Student 5,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Large Scale Optimization for Data Science', 'Optimization Methods in Finance']"
Student 6,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Generalised Regression Models', 'Simulation', 'Statistical Methodology']"
Student 7,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Optimization Methods in Finance', 'Simulation', 'Credit Scoring']"
Student 8,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Operational Research in the Energy Industry', 'Credit Scoring', 'Optimization Methods in Finance']"
Student 9,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Time Series', 'Operational Research in the Energy Industry', 'Optimization Methods in Finance']"
Student 10,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming', 'Large Scale Optimization for Data Science', 'Biostatistics']"
Student 11,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Large Scale Optimization for Data Science', 'Stochastic Modelling', 'Statistical Programming']"
Student 12,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Operational Research in the Energy Industry', 'Stochastic Modelling', 'Credit Scoring']"
Student 13,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Risk and Logistics', 'Stochastic Modelling', 'Optimization Methods in Finance']"
Student 14,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Large Scale Optimization for Data Science', 'Python Programming', 'Risk and Logistics']"
Student 15,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming', 'Simulation', 'Python Programming']"
Student 16,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Large Scale Optimization for Data Science', 'Optimization Methods in Finance', 'Machine Learning in Python']"
Student 17,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Machine Learning in Python', 'Python Programming', 'Operational Research in the Energy Industry']"
Student 18,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Statistical Methodology', 'Biostatistics', 'Generalised Regression Models']"
Student 19,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Python Programming', 'Operational Research in the Energy Industry', 'Biostatistics']"
Student 20,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Python Programming', 'Optimization Methods in Finance', 'Stochastic Modelling']"
Student 21,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Operational Research in the Energy Industry', 'Biostatistics', 'Credit Scoring']"
Student 22,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Generalised Regression Models', 'Operational Research in the Energy Industry', 'Optimization Methods in Finance']"
Student 23,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Large Scale Optimization for Data Science', 'Time Series', 'Topics in Applied Operational Research']"
Student 24,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Time Series', 'Large Scale Optimization for Data Science', 'Python Programming']"
Student 25,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Python Programming', 'Credit Scoring', 'Stochastic Modelling']"
Student 26,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Optimization Methods in Finance', 'Risk and Logistics', 'Statistical Methodology']"
Student 27,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Credit Scoring', 'Topics in Applied Operational Research', 'Statistical Methodology']"
Student 28,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Operational Research in the Energy Industry', 'Credit Scoring', 'Python Programming']"
Student 29,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Simulation', 'Topics in Applied Operational Research']"
Student 30,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Topics in Applied Operational Research', 'Stochastic Modelling', 'Credit Scoring']"
Student 31,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Python Programming', 'Statistical Programming', 'Large Scale Optimization for Data Science']"
Student 32,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Biostatistics']"
Student 33,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Machine Learning in Python']"
Student 34,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Generalised Regression Models']"
Student 35,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Python Programming']"
Student 36,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Statistical Methodology']"
Student 37,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Operational Research in the Energy Industry']"
Student 38,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Generalised Regression Models']"
Student 39,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Operational Research in the Energy Industry']"
Student 40,"['Fundamentals of Optimization', 'Fundamentals of Operational Research', 'Methodology, Modelling and Consulting Skills', 'Simulation', 'Stochastic Modelling', 'Time Series']"
Student 41,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Introductory Probability and Statistics', 'Fundamentals of Optimization', 'Applied Stochastic Differential Equations']"
Student 42,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Bayesian Theory', 'Industrial Mathematics', 'Statistical Programming']"
Student 43,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Industrial Mathematics', 'Stochastic Modelling', 'Applied Stochastic Differential Equations']"
Student 44,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Statistical Programming', 'Fundamentals of Optimization', 'Applied Stochastic Differential Equations']"
Student 45,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Industrial Mathematics', 'Stochastic Modelling', 'Fundamentals of Optimization']"
Student 46,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Applied Stochastic Differential Equations', 'Industrial Mathematics', 'Statistical Programming']"
Student 47,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Statistical Methodology', 'Statistical Programming', 'Bayesian Theory']"
Student 48,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Statistical Programming', 'Industrial Mathematics', 'Fundamentals of Optimization']"
Student 49,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Statistical Methodology', 'Applied Stochastic Differential Equations', 'Introductory Probability and Statistics']"
Student 50,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Statistical Programming', 'Applied Stochastic Differential Equations', 'Fundamentals of Optimization']"
Student 51,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Bayesian Theory', 'Statistical Methodology', 'Applied Stochastic Differential Equations']"
Student 52,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Bayesian Theory', 'Introductory Probability and Statistics', 'Applied Stochastic Differential Equations']"
Student 53,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Stochastic Modelling', 'Fundamentals of Optimization', 'Statistical Programming']"
Student 54,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Introductory Probability and Statistics', 'Fundamentals of Optimization', 'Stochastic Modelling']"
Student 55,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Fundamentals of Optimization', 'Introductory Probability and Statistics', 'Industrial Mathematics']"
Student 56,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Stochastic Modelling', 'Statistical Programming', 'Industrial Mathematics']"
Student 57,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Statistical Methodology', 'Fundamentals of Optimization', 'Stochastic Modelling']"
Student 58,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Applied Stochastic Differential Equations', 'Bayesian Theory', 'Statistical Methodology']"
Student 59,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Bayesian Theory', 'Stochastic Modelling', 'Industrial Mathematics']"
Student 60,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Applied Stochastic Differential Equations', 'Statistical Programming', 'Stochastic Modelling']"
Student 61,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Fundamentals of Optimization', 'Introductory Probability and Statistics', 'Applied Stochastic Differential Equations']"
Student 62,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Stochastic Modelling', 'Statistical Programming', 'Industrial Mathematics']"
Student 63,"['Numerical Linear Algebra', 'Python Programming', 'Research Skills for Computational Applied Mathematics', 'Industrial Mathematics', 'Introductory Probability and Statistics', 'Fundamentals of Optimization']"
Student 64,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Bayesian Theory', 'Blockchains and Distributed Ledgers*']"
Student 65,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Finance, Risk and Uncertainty', 'Programming Skills']"
Student 66,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Programming Skills', 'Finance, Risk and Uncertainty']"
Student 67,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Programming Skills', 'Finance, Risk and Uncertainty', 'Blockchains and Distributed Ledgers']"
Student 68,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Finance, Risk and Uncertainty', 'Programming Skills']"
Student 69,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Programming Skills', 'Bayesian Theory']"
Student 70,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Bayesian Theory', 'Programming Skills']"
Student 71,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Programming Skills', 'Blockchains and Distributed Ledgers']"
Student 72,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Programming Skills', 'Bayesian Theory']"
Student 73,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Blockchains and Distributed Ledgers', 'Bayesian Theory']"
Student 74,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Blockchains and Distributed Ledgers', 'Programming Skills']"
Student 75,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Bayesian Theory', 'Finance, Risk and Uncertainty', 'Programming Skills']"
Student 76,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Blockchains and Distributed Ledgers', 'Programming Skills']"
Student 77,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Programming Skills', 'Bayesian Theory']"
Student 78,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Programming Skills', 'Bayesian Theory']"
Student 79,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Bayesian Theory', 'Finance, Risk and Uncertainty', 'Blockchains and Distributed Ledgers']"
Student 80,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Bayesian Theory', 'Programming Skills']"
Student 81,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Bayesian Theory', 'Finance, Risk and Uncertainty', 'Programming Skills']"
Student 82,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Bayesian Theory', 'Programming Skills']"
Student 83,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Programming Skills', 'Blockchains and Distributed Ledgers', 'Finance, Risk and Uncertainty']"
Student 84,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Bayesian Theory', 'Programming Skills', 'Finance, Risk and Uncertainty']"
Student 85,"['Stochastic Analysis in Finance', 'Discrete-Time Finance', 'Python Programming', 'Blockchains and Distributed Ledgers', 'Programming Skills', 'Finance, Risk and Uncertainty']"
Student 86,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Finance, Risk and Uncertainty', 'Python Programming', 'Fundamentals of Operational Research']"
Student 87,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Fundamentals of Operational Research', 'Stochastic Modelling', 'Finance, Risk and Uncertainty']"
Student 88,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Fundamentals of Operational Research', 'Finance, Risk and Uncertainty', 'Stochastic Modelling']"
Student 89,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Python Programming', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 90,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Finance, Risk and Uncertainty', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 91,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Stochastic Modelling', 'Finance, Risk and Uncertainty', 'Fundamentals of Operational Research']"
Student 92,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Fundamentals of Operational Research']"
Student 93,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Fundamentals of Operational Research', 'Stochastic Modelling', 'Finance, Risk and Uncertainty']"
Student 94,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Python Programming', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 95,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Finance, Risk and Uncertainty', 'Python Programming', 'Stochastic Modelling']"
Student 96,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Stochastic Modelling', 'Fundamentals of Operational Research', 'Finance, Risk and Uncertainty']"
Student 97,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Python Programming', 'Stochastic Modelling', 'Fundamentals of Operational Research']"
Student 98,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Stochastic Modelling', 'Fundamentals of Operational Research', 'Python Programming']"
Student 99,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Fundamentals of Operational Research', 'Stochastic Modelling', 'Python Programming']"
Student 100,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Stochastic Modelling']"
Student 101,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Fundamentals of Operational Research', 'Python Programming', 'Stochastic Modelling']"
Student 102,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Fundamentals of Operational Research', 'Finance, Risk and Uncertainty', 'Stochastic Modelling']"
Student 103,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Finance, Risk and Uncertainty', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 104,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Finance, Risk and Uncertainty', 'Stochastic Modelling', 'Fundamentals of Operational Research']"
Student 105,"['Discrete-Time Finance', 'Fundamentals of Optimization', 'Stochastic Analysis in Finance', 'Python Programming', 'Finance, Risk and Uncertainty', 'Fundamentals of Operational Research']"
Student 106,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Statistical Programming', 'Generalised Regression Models']"
Student 107,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Generalised Regression Models', 'Statistical Programming']"
Student 108,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Statistical Methodology', 'Statistical Programming']"
Student 109,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Numerical Linear Algebra', 'Statistical Methodology']"
Student 110,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Python Programming', 'Statistical Programming']"
Student 111,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Generalised Regression Models', 'Statistical Methodology']"
Student 112,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Python Programming', 'Statistical Programming']"
Student 113,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Statistical Methodology', 'Python Programming']"
Student 114,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Numerical Linear Algebra', 'Python Programming']"
Student 115,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Python Programming', 'Statistical Methodology']"
Student 116,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Generalised Regression Models', 'Python Programming']"
Student 117,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Generalised Regression Models', 'Numerical Linear Algebra']"
Student 118,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Python Programming', 'Generalised Regression Models']"
Student 119,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Numerical Linear Algebra', 'Statistical Programming']"
Student 120,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Statistical Programming', 'Generalised Regression Models']"
Student 121,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Statistical Methodology', 'Numerical Linear Algebra']"
Student 122,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Python Programming', 'Numerical Linear Algebra']"
Student 123,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Python Programming', 'Statistical Programming']"
Student 124,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Generalised Regression Models', 'Numerical Linear Algebra']"
Student 125,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Statistical Programming', 'Numerical Linear Algebra']"
Student 126,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Statistical Methodology', 'Statistical Programming']"
Student 127,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Python Programming', 'Numerical Linear Algebra']"
Student 128,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Generalised Regression Models', 'Numerical Linear Algebra']"
Student 129,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Introductory Probability and Statistics', 'Numerical Linear Algebra']"
Student 130,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Introductory Probability and Statistics', 'Numerical Linear Algebra']"
Student 131,"['Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Methodology, Modelling and Consulting Skills', 'Stochastic Modelling', 'Generalised Regression Models', 'Statistical Methodology']"
Student 132,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 133,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 134,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 135,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 136,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 137,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 138,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 139,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 140,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 141,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 142,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 143,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 144,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 145,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 146,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 147,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 148,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 149,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 150,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 151,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 152,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 153,"['Bayesian Theory', 'Fundamentals of Operational Research', 'Fundamentals of Optimization', 'Generalised Regression Models', 'Methodology, Modelling and Consulting Skills', 'Statistical Programming']"
Student 154,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Python Programming']"
Student 155,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Statistical Methodology']"
Student 156,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Fundamentals of Optimization']"
Student 157,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 158,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Optimization']"
Student 159,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Stochastic Modelling']"
Student 160,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 161,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Fundamentals of Operational Research']"
Student 162,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Stochastic Modelling']"
Student 163,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Fundamentals of Optimization']"
Student 164,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 165,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 166,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 167,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 168,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Stochastic Modelling']"
Student 169,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 170,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Optimization']"
Student 171,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 172,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Fundamentals of Optimization']"
Student 173,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Statistical Methodology']"
Student 174,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Fundamentals of Operational Research']"
Student 175,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 176,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 177,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Fundamentals of Optimization']"
Student 178,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 179,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 180,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 181,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Python Programming']"
Student 182,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Optimization']"
Student 183,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Statistical Methodology']"
Student 184,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 185,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 186,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Statistical Methodology']"
Student 187,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Optimization']"
Student 188,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Stochastic Modelling']"
Student 189,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Statistical Methodology']"
Student 190,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Python Programming']"
Student 191,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Python Programming']"
Student 192,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Statistical Methodology']"
Student 193,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 194,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Python Programming']"
Student 195,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Stochastic Modelling']"
Student 196,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 197,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Fundamentals of Optimization']"
Student 198,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Optimization']"
Student 199,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Fundamentals of Optimization']"
Student 200,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Python Programming']"
Student 201,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 202,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 203,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 204,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Statistical Methodology']"
Student 205,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 206,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Python Programming']"
Student 207,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Optimization']"
Student 208,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 209,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Stochastic Modelling']"
Student 210,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Fundamentals of Optimization']"
Student 211,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Statistical Methodology']"
Student 212,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Statistical Methodology']"
Student 213,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Python Programming']"
Student 214,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 215,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Stochastic Modelling']"
Student 216,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Fundamentals of Operational Research']"
Student 217,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 218,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Python Programming']"
Student 219,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Stochastic Modelling']"
Student 220,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Statistical Methodology']"
Student 221,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Fundamentals of Operational Research']"
Student 222,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Fundamentals of Operational Research']"
Student 223,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Fundamentals of Optimization']"
Student 224,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Fundamentals of Optimization']"
Student 225,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Stochastic Modelling']"
Student 226,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Fundamentals of Optimization']"
Student 227,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Optimization']"
Student 228,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Statistical Methodology']"
Student 229,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Fundamentals of Operational Research']"
Student 230,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Operational Research', 'Python Programming']"
Student 231,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 232,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Fundamentals of Optimization', 'Python Programming']"
Student 233,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Python Programming']"
Student 234,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Statistical Methodology', 'Fundamentals of Operational Research']"
Student 235,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Stochastic Modelling', 'Statistical Methodology']"
Student 236,"['Bayesian Theory', 'Extended Statistical Programming', 'Generalised Regression Models', 'Python Programming', 'Statistical Methodology']"
"""